Update palestra-transmissao-ao-vivo.md
pythonbrasil/pybr2021-org pull request #189
Opened 2021-08-06 11:13 UTC by joaomaia7

2021-08-06 12:18 UTC, cecivieira commented
from: @joaomaia7 
realizei algumas mudanças de ordem gramatical e de apresentação do documento, apenas. mandei Pull Request. fique à vontade para sugerir modificações.

2021-08-07 15:33 UTC, cecivieira requested changes
@joaomaia7 Ficou massa!
Percebi que o emojin :desktop: (que eu coloquei) não renderizou, aqui no github o emojin é :desktop_computer: . Tu acha interessante trocar?

2021-08-10 00:05 UTC, alynnefs commented
a única coisa que impede o merge é o emoji? já que vai ficar aqui no github, voto por trocar (:

2021-08-10 16:54 UTC, joaomaia7 commented
@cecivieira tudo bem trocar o emoji.

2021-08-11 18:44 UTC, merged

2021-08-11 18:44 UTC, cecivieira commented
@alynnefs @joaomaia7 atualizei o emojin